package gov.va.vinci.chartreview.model.schema;

// Generated Mar 8, 2011 3:41:01 PM by Hibernate Tools 3.2.4.GA

import org.apache.commons.lang.builder.ToStringBuilder;

import javax.persistence.*;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Date;
import java.util.UUID;

/**
 * AttributeDefOptionDef generated by hbm2java
 */
@Entity
public class AttributeDefOptionDef implements java.io.Serializable, Comparable<AttributeDefOptionDef>
{

    private String id;
    private String name = "New_Option";
    private AttributeDef attributeDef;
    private Timestamp version = new Timestamp((new Date()).getTime());

	public AttributeDefOptionDef() {
	}

    public AttributeDefOptionDef(AttributeDefOptionDef obj) {
        this(obj, false);
    }

    public AttributeDefOptionDef(AttributeDefOptionDef obj, boolean augmentName) {
        this (
                UUID.randomUUID().toString(),
                augmentName ? obj.name + "_copy" : obj.name
        );
    }

    public AttributeDefOptionDef(String uid, String name) {
        this.id =  uid;
        this.name = name;
	}

    @Id
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Column
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @ManyToOne
    public AttributeDef getAttributeDef() {
        return attributeDef;
    }

    public void setAttributeDef(AttributeDef attributeDef) {
        this.attributeDef = attributeDef;
    }

    @Version
    public Timestamp getVersion() {
        return version;
    }

    public void setVersion(Timestamp version) {
        this.version = version;
    }

    public String toString() {
        return ToStringBuilder.reflectionToString(this);
    }

    public int compareTo(AttributeDefOptionDef compObj) {

        return compare(this, compObj);
    }

    static int compare(AttributeDefOptionDef obj1, AttributeDefOptionDef obj2) {

        String objName1 = obj1.getName();
        String objName2 = obj2.getName();
        return objName1.compareTo(objName2);
    }

    @Transient
    public String getSchemaRef() {
        return "annotationSchema:" + this.getAttributeDef().getAnnotationSchema().getId() +
                ";attributeDef:" + this.getAttributeDef().getId() + ";attributeDefOptionDef:" + getId();
    }
}
